import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import { Providers } from './providers';
import { Toaster } from '@/components/ui/sonner';

import './globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const rubik = Rubik({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700', '800', '900'],
    variable: '--font-rubik',
    display: 'swap',
});

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${rubik.variable} antialiased`}>
                <Providers>{children}</Providers>
                <Toaster />
            </body>
        </html>
    );
}
